#
# Credits: https://raw.githubusercontent.com/StarterSquad/prudentia/develop/prudentia/tasks/nginx.yml
#

---
  - name: Nginx | Check if is present
    command: test -x /usr/sbin/nginx
    when: ansible_os_family == "Debian"
    ignore_errors: yes
    register: nginx_present
    tags: nginx

  - block:

    - name: Nginx | Add GPG key to apt keyring
      apt_key: url=http://nginx.org/keys/nginx_signing.key state=present
      when: nginx_present|failed
      become: yes
      tags:
        - nginx

    - name: Nginx | Add Debian apt repository
      apt_repository: repo="deb http://nginx.org/packages/debian/ {{ansible_distribution_release}} nginx"
      when: ansible_os_family == "Debian" and ansible_distribution != "Ubuntu" and nginx_present|failed
      tags: nginx
      become: yes

    - name: Nginx | Add Ubuntu apt repository
      apt_repository: repo="deb http://nginx.org/packages/ubuntu/ {{ansible_distribution_release}} nginx"
      when: ansible_distribution == "Ubuntu" and nginx_present|failed
      tags: nginx
      become: yes

    - name: Nginx | Install (apt)
      apt: update-cache=yes force=yes state=present pkg=nginx
      when: nginx_present|failed
      tags: nginx
      become: yes
    when: ansible_os_family == "Debian"

  - block:

    - name: Nginx | Add  RPM official nginx key
      rpm_key: key=http://nginx.org/keys/nginx_signing.key
      when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'
      tags: nginx
      become: yes

    - name: Nginx | add YUM official nginx repository
      template: src="{{role_dir}}/templates/nginx/nginx.repo.j2" dest=/etc/yum.repos.d/nginx.repo
      when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'
      tags: nginx
      become: yes

    - name: Nginx | Install (OS specific yum/dng)
      package: state=present name=nginx
      tags: nginx
      become: yes

    when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS' or ansible_distribution == 'Fedora'


  - name: Nginx | Create sites available/enabled directories
    file: path={{item}} state=directory mode=0755
    with_items:
      - /etc/nginx/sites-available
      - /etc/nginx/sites-enabled
    become: yes
    tags: 
      - nginx


  - name: Nginx | Configure include sites-enabled
    lineinfile: dest=/etc/nginx/nginx.conf regexp=".*sites-enabled.*" line="    include /etc/nginx/sites-enabled/*;" insertbefore="}" state=present
    become: yes
    tags: 
      - nginx


  - name: Nginx | Disable default site
    file: path=/etc/nginx/default.conf state=absent
    when:  nginx_present|failed
    become: yes
    tags: 
      - nginx


  - name: Nginx | Uncomment server_names_hash_bucket_size
    lineinfile: dest=/etc/nginx/nginx.conf regexp="^(\s*)#\s*server_names_hash_bucket_size" line="\1server_names_hash_bucket_size 64;" backrefs=yes
    become: yes
    tags: 
      - nginx

  - name: Nginx | Reload
    service: name=nginx state=reloaded enabled=yes
    when: nginx_present|failed and docker_test is not defined
    become: yes
    tags: 
      - nginx

