---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Display pre-task message
      ansible.builtin.debug:
        msg: "Pre tasks section for {{ ansible_host }}"

    - name: Set default facts
      ansible.builtin.set_fact:
        remote_ip_address: "{{ ansible_host }}"

    - name: Include default vars
      ansible.builtin.include_vars: "vars/playbook_vars.yml"

  roles:
    - role: "sa-nginx"


#- name: Apply box play
#  import_playbook: ../../playbook.yml

